server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_shop_app?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    max-file-size: 10MB
    max-request-file: 10MB
api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=